spring:
  datasource:
    username: root
    password: 123456789a
    url: jdbc:mysql://localhost:3306/duantotnghiep
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true
  servlet:
    max-file-size: 2MB
    multipart:
      max-request-size: 2MB
  security:
    user:
      name: anhduc
      password: 123

  mail:
    host: smtp.gmail.com
    post: 587
    username: vuttph25379@fpt.edu.vn
    password: qhycocmzpzpehddo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true